/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import controllers.RegionController;
import entities.Employee;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tools.MyConnection;

/**
 *
 * @author MUHAMMAD BIN ZANDRA
 */
public class EmployeeView extends javax.swing.JInternalFrame {

    private EmployeeController employeeController;
    private final ViewProccess viewProccess;
    private final String[] header = {"Employee ID", "First Name", "Last Name", "EMail", "Phone", "Hire", "Job ID", "Salary", "Commission", "Manager", "Depaerment"};
    private final String[] categories;
    private final Connection connection;

    /**
     * Creates new form EmployeeView
     */
    public EmployeeView(Connection connection) {
        this.connection = connection;
                 
        this.categories = new String[]{"employee_id", "first_name", "last_name", "email", "phone_number", "hire_date", "job_id", "salary", "commissio_pct", "manager_id", "department_id"};
        initComponents();
      
        this.employeeController = new EmployeeController(connection);
        this.viewProccess = new ViewProccess();
        this.bindingTable();
        this.loadSearchComboBox();
        this.loadDetailDepartment();
        this.loadDetailJob();

        this.reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTabel = new javax.swing.JTable();
        employeePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        employeeIdTextField = new javax.swing.JTextField();
        employeeFistnameTextField = new javax.swing.JTextField();
        employeeLastNametextField = new javax.swing.JTextField();
        employeeEmailTextField = new javax.swing.JTextField();
        employeePhoneTextField = new javax.swing.JTextField();
        employeeHireDateeTextField = new javax.swing.JTextField();
        employeeSalaryTextField = new javax.swing.JTextField();
        employeeCOmmissionTextField = new javax.swing.JTextField();
        employeeManagerTextField = new javax.swing.JTextField();
        employeeSaveButton = new javax.swing.JButton();
        employeeDropButton = new javax.swing.JButton();
        employeeComboJOB = new javax.swing.JComboBox<>();
        employeeComboDepartment = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        employeeSearchTextField = new javax.swing.JTextField();
        employeeSearchComboList = new javax.swing.JComboBox<>();
        employeeSeachButtonList = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Employees");

        employeeTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        employeeTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeTabel);

        employeePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Employees"));

        jLabel1.setText("Employee ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Email");

        jLabel5.setText("Phone");

        jLabel6.setText("Hire Date");

        jLabel7.setText("Job ID");

        jLabel8.setText("Salary");

        jLabel9.setText("Commissio PCT");

        jLabel10.setText("Manager ID");

        jLabel11.setText("Department ID");

        employeeSalaryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSalaryTextFieldActionPerformed(evt);
            }
        });

        employeeSaveButton.setText("Save");
        employeeSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSaveButtonActionPerformed(evt);
            }
        });

        employeeDropButton.setText("Drop");
        employeeDropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeDropButtonActionPerformed(evt);
            }
        });

        employeeComboJOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeComboJOBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addComponent(employeeLastNametextField))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeFistnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePanelLayout.createSequentialGroup()
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePanelLayout.createSequentialGroup()
                                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(54, 54, 54))
                            .addGroup(employeePanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39)))
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeeEmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(employeePhoneTextField)
                            .addComponent(employeeHireDateeTextField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(58, 58, 58)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeComboJOB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(employeeCOmmissionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(34, 34, 34)
                        .addComponent(employeeManagerTextField))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(employeeComboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97))
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeeSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeDropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(employeeHireDateeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(employeePanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(employeeIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(employeeFistnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(employeeLastNametextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(employeeEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(employeePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(employeePanelLayout.createSequentialGroup()
                                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(employeePanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel7)
                                        .addGap(9, 9, 9)
                                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(employeeSalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(employeeCOmmissionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(employeeManagerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(employeeComboJOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeComboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(32, 32, 32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeSaveButton)
                    .addComponent(employeeDropButton))
                .addContainerGap())
        );

        employeeSearchComboList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "First Name", "Last Name", "Email", "Phone", "Hire Date", "Job Id", "Salary", "Commission", "Manager ID", "Department ID" }));
        employeeSearchComboList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSearchComboListActionPerformed(evt);
            }
        });

        employeeSeachButtonList.setText("Search");
        employeeSeachButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSeachButtonListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(employeeSearchComboList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeSeachButtonList)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeSeachButtonList)
                    .addComponent(employeeSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeSearchComboList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeSalaryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSalaryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeSalaryTextFieldActionPerformed

    private void employeeTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTabelMouseClicked
        this.mouseClicked(employeeTabel.getSelectedRow());
    }//GEN-LAST:event_employeeTabelMouseClicked

    private void employeeSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSaveButtonActionPerformed

        this.saveOrEdit(employeeIdTextField.getText(),
                employeeFistnameTextField.getText(),
                employeeLastNametextField.getText(),
                employeeEmailTextField.getText(),
                employeePhoneTextField.getText(),
                employeeHireDateeTextField.getText(),
                employeeComboJOB.getSelectedItem().toString(),
                employeeSalaryTextField.getText(),
                employeeCOmmissionTextField.getText(),
                employeeManagerTextField.getText(),
                employeeComboDepartment.getSelectedItem().toString(),
                employeeIdTextField.isEnabled());
    }//GEN-LAST:event_employeeSaveButtonActionPerformed

    private void employeeDropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDropButtonActionPerformed
        this.drop(Integer.parseInt(employeeIdTextField.getText()));
    }//GEN-LAST:event_employeeDropButtonActionPerformed

    private void employeeSeachButtonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSeachButtonListActionPerformed
        this.searchTable(this.viewProccess.getCategory(this.categories, employeeSearchComboList), employeeSearchTextField.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_employeeSeachButtonListActionPerformed

    private void employeeSearchComboListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSearchComboListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeSearchComboListActionPerformed

    private void employeeComboJOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeComboJOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeComboJOBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField employeeCOmmissionTextField;
    private javax.swing.JComboBox<String> employeeComboDepartment;
    private javax.swing.JComboBox<String> employeeComboJOB;
    private javax.swing.JButton employeeDropButton;
    private javax.swing.JTextField employeeEmailTextField;
    private javax.swing.JTextField employeeFistnameTextField;
    private javax.swing.JTextField employeeHireDateeTextField;
    private javax.swing.JTextField employeeIdTextField;
    private javax.swing.JTextField employeeLastNametextField;
    private javax.swing.JTextField employeeManagerTextField;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JTextField employeePhoneTextField;
    private javax.swing.JTextField employeeSalaryTextField;
    private javax.swing.JButton employeeSaveButton;
    private javax.swing.JButton employeeSeachButtonList;
    private javax.swing.JComboBox<String> employeeSearchComboList;
    private javax.swing.JTextField employeeSearchTextField;
    private javax.swing.JTable employeeTabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    public void bindingTable() {
        this.viewProccess.viewTable(employeeTabel, header,
                this.employeeController.bindingSort(categories[0], "asc"));
    }

    public void searchTable(String category, String data) {
        this.viewProccess.viewTable(employeeTabel, header,
                this.employeeController.find(category, data));
    }

    public void loadSearchComboBox() {
        this.viewProccess.loadSearchComboBox(employeeSearchComboList, header);
    }

    public void drop(int employeeId) {
        if (this.viewProccess.dropConfirm(this)) {
            this.viewProccess.dropData(this, this.employeeController.drop(employeeId));
        }
        this.reset();
    }

    public void saveOrEdit(String employeeId, String firstName, String LastName, String email, String phoneNumber, String hireDate, String jobId, String salary, String commissionPct, String managerId, String departmentId, boolean isSave) {
        boolean flag = false;
        if (isSave) {
            flag = this.employeeController.save(employeeId, firstName, LastName, email, phoneNumber, hireDate, jobId, salary, commissionPct, managerId, departmentId);
        } else {
            flag = this.employeeController.edit(employeeId, firstName, LastName, email, phoneNumber, hireDate, jobId, salary, commissionPct, managerId, departmentId);
        }
        this.viewProccess.saveData(this, flag, isSave);

    }

    public void mouseClicked(int row) {
        employeeIdTextField.setEnabled(false);
        employeeDropButton.setEnabled(true);
        employeeIdTextField.setText(employeeTabel.getValueAt(row, 0).toString());
        employeeFistnameTextField.setText(employeeTabel.getValueAt(row, 1).toString());
        employeeLastNametextField.setText(employeeTabel.getValueAt(row, 2).toString());
        employeeEmailTextField.setText(employeeTabel.getValueAt(row, 3).toString());
        employeePhoneTextField.setText(employeeTabel.getValueAt(row, 4).toString());
        employeeHireDateeTextField.setText(employeeTabel.getValueAt(row, 5).toString());
        employeeComboJOB.getSelectedIndex();
        employeeSalaryTextField.setText(employeeTabel.getValueAt(row, 7).toString());
        employeeCOmmissionTextField.setText(employeeTabel.getValueAt(row, 8).toString());
        employeeManagerTextField.setText(employeeTabel.getValueAt(row, 9).toString());

        employeeComboDepartment.getSelectedIndex();
    }
/**
 * fungsi menampilkan nama combobox
 */
    public void loadCombobox() {
        this.viewProccess.loadSearchComboBox(employeeSearchComboList, header);

    }
  /**
   * fungsi menampikan detail job
   */
    public void loadDetailJob() {
        this.viewProccess.loadDetails(employeeComboJOB, new EmployeeController(connection).binding(), 6);
    }
 /**
  * fungsi menampilkan data detaildepartment
  */
    public void loadDetailDepartment() {
        this.viewProccess.loadDetails(employeeComboDepartment, new EmployeeController(connection).binding(), 10);
    }
/**
 * fungsi mereset semua kolom 
 */
    public void reset() {
        employeeIdTextField.setEnabled(true);
        employeeIdTextField.setEditable(false);
        employeeIdTextField.setText(this.employeeController.getAutoId());
        employeeFistnameTextField.setText("");
        employeeLastNametextField.setText("");
        employeeEmailTextField.setText("");
        employeePhoneTextField.setText("");
        employeeHireDateeTextField.setText("");
        employeeSalaryTextField.setText("");
        employeeCOmmissionTextField.setText("");
        employeeManagerTextField.setText("");
        employeeSearchTextField.setText("");
        employeeSearchTextField.setText("");
        this.bindingTable();
        employeeDropButton.setEnabled(false);
    }
}
